apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logmetrics.fullname" . }}
  labels:
    {{- include "logmetrics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "logmetrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "logmetrics.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "logmetrics.serviceAccountName" . }}
      containers:
        - name: logmetrics
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --config=/etc/logmetrics/config.yaml
            - --incluster
          ports:
            - name: metrics
              containerPort: 9748
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: metrics
          readinessProbe:
            httpGet:
              path: /health
              port: metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/logmetrics
      volumes:
        - name: config
          configMap:
            name: {{ include "logmetrics.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
